name: project-sanbercode
services:
  postgresql:
    image: postgres:17.6
    container_name: last_project_sanbercode_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5439:5432"
    volumes:
      - ./postgres/INIT.sql:/docker-entrypoint-initdb.d/INIT.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 11s
      timeout: 6s
      retries: 7
    networks:
      - app_network
  
  inventory_optimizer_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: last_project_sanbercode:latest
    container_name: inventory-optimizer-app
    restart: unless-stopped
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - APP_PORT=:${APP_PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSLMODE=${DB_SSLMODE}
      - DB_TIMEZONE=${DB_TIMEZONE}
      - JWT_SECRET=${JWT_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - MODEL=${MODEL}
    networks:
      - app_network
    depends_on:
      postgresql:
        condition: service_healthy

networks:
  app_network:
    driver: bridge